using UnityEngine;

namespace MonsterBattleArena
{
    public abstract class GameResource : ScriptableObject
    {
        // NOTE: Id will be generated by the editor script
        [SerializeField, GUID] protected string _id;
        [SerializeField] protected string _name;
        [SerializeField] protected Sprite _icon;
        [SerializeField, TextArea] protected string _description;

        public string Id { get => _id; }
        public string Name { get => _name; }
        public Sprite Icon { get => _icon; }
        public string Description { get => _description; }
    }
}
